### ISSUE TITLE
[Rust]  Implement metrics framework

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#95] opened 2021-04-26 13:18 UTC
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-9552

It is important for users to be able to debug query performance and each operator is capable of collecting important metrics, like # of input and output batches and rows, as well as elapsed time spent doing different types of processing.

We should design traits for metrics reporting so that other projects using DataFusion can access these metrics and make them available for users to see.

**Comment by alamb** [comment] 2021-04-26 13:18
Comment from Andrew Lamb(alamb) @ 2021-04-26T12:32:47.084+0000:
<pre>Migrated to github: https://github.com/apache/arrow-rs/issues/90</pre>

**Comment by andygrove** [comment] 2021-07-03 20:01
Duplicate of https://github.com/apache/arrow-datafusion/issues/21

**Closed by andygrove** 2021-07-03 20:01 UTC
Labels: datafusion
