### ISSUE TITLE
change` date_part` return types to f64

### ISSUE THREAD

**Issue by waitingkuo** [apache/arrow-datafusion#3997] opened 2022-10-28 14:11 UTC
`date_part` currently  returns `i32` which might lose some information, e.g.

```bash
❯ select date_part('second', timestamp '2000-01-01T00:00:00.1');
+--------------------------------------------------------+
| datepart(Utf8("second"),Utf8("2000-01-01T00:00:00.1")) |
+--------------------------------------------------------+
| 0                                                      |
+--------------------------------------------------------+
1 row in set. Query took 0.000 seconds.
```

while postgresql returns double precision
```bash
willy=# select date_part('second', timestamp '2000-01-01T00:00:00.1');
 date_part 
-----------
       0.1
(1 row)
```

is it recommended to follow postgresql's return type?
if it is preferred, perhaps we could do a separate pr to deal with this

change it to double precision

**Describe the solution you'd like**

**Describe alternatives you've considered**

perhaps we could consider return decimals instead to align with extract to return decimal. postgres doc mentions this:
```
For historical reasons, the date_part function returns values of type double precision. 
This can result in a loss of precision in certain uses. Using extract is recommended instead.
```
https://www.postgresql.org/docs/current/functions-datetime.html

**Additional context**

**Comment by comphead** [comment] 2022-10-29 21:06
@waitingkuo may I try this?

**Comment by waitingkuo** [comment] 2022-10-30 07:38
> @waitingkuo may I try this?

sure, please try it~

**Comment by comphead** [comment] 2022-11-01 15:28
@waitingkuo the problem is  `date_part` calls for `arrow::compute::kernels::temporal::second` which is i32, and they dont have millisecond support. Do you think its good idea to implement milliseconds by ourselves?

**Comment by waitingkuo** [comment] 2022-11-01 16:51
@comphead 

`arrow-rs` uses `chrono-rs` to extract these date parts. Chono-rs does have [nanosecond](https://docs.rs/chrono/latest/chrono/trait.Timelike.html#tymethod.nanosecond) while arrow-rs doesn't have.

We could extend `arrow-rs` to support `nanosecond` and then get back to this issue.

I think adding nanosecond support in `arrow-rs` is a `good start issue`. If you're interested in, I'm happy to help you to figure out the codes to modify. Basically, you could follow the `second`'s logic to do so
https://github.com/apache/arrow-rs/blob/master/arrow/src/compute/kernels/temporal.rs#L723-L764

I could help to send a pr to arrow-rs as well

**Comment by waitingkuo** [comment] 2022-11-01 16:51
cc @alamb

**Comment by comphead** [comment] 2022-11-01 17:08
@waitingkuo thanks for the details, let me try to add the ticket and PR to arrow-rs.

**Comment by comphead** [comment] 2022-11-01 17:18
Related arrow-rs ticket https://github.com/apache/arrow-rs/issues/2995

**Comment by comphead** [comment] 2022-11-03 05:17
@waitingkuo the https://github.com/apache/arrow-rs/issues/2995 merged, should we wait for next arrow-rs version? How it usually happens?

**Comment by waitingkuo** [comment] 2022-11-03 08:06
@comphead thank you. i think we need to wait for 27.0.0 . 26.0.0 is just fixed. It normally released 1 or 2 times a month

**Comment by comphead** [comment] 2022-11-14 23:59
waiting for #4199

**Closed** 2022-12-06 21:17 UTC
Labels: enhancement
