### ISSUE TITLE
sql("explain  select  1") raise an error

### ISSUE THREAD

**Issue by l1t1** [apache/arrow-datafusion#9319] opened 2024-02-23 00:04 UTC
### Describe the bug

I use sql() to explain an query, it raised an error.
`sql("explain analyze select 1")` also has the issue

### To Reproduce

```python
import datafusion
ctx=datafusion.SessionContext()
ctx.sql("explain select 1")
```
outputs
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception: Internal error: Unsupported logical plan: Explain must be root of the plan.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

### Expected behavior

it output the plan of the query

### Additional context

OS windows /Linux
python 3.8 /3.10
datafusion 35.0.0

**Comment by SteveLauC** [comment] 2024-02-23 02:04
Cannot reproduce with the rust library DataFusion 36:

```sh
$ rg datafusion Cargo.toml
18:datafusion = "36.0.0"

$ cat src/main.rs
#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<()> {
    let ctx = SessionContext::new();
    let sql = "explain select 1";
    let df = ctx.sql("explain select 1").await?;
    df.show().await?;

    Ok(())
}

$ cargo r -q
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

**Comment by SteveLauC** [comment] 2024-02-23 02:18
> Internal error: Unsupported logical plan: Explain must be root of the plan.

BTW, using the rust library will give you the following logical plan:

```
Explain
  Projection: Int64(1)
    EmptyRelation
```

**Comment by l1t1** [comment] 2024-02-23 02:19
my env.
OS windows /Linux
python 3.8 /3.10
datafusion               35.0.0

**Comment by SteveLauC** [comment] 2024-02-23 02:24
I am also on Linux, and with DataFusion Rust library 35.0.0, I got the same results as 36.0.0, seems to be an issue with the Python lib.

**Comment by guojidan** [comment] 2024-02-23 02:33
hi @l1t1 , Maybe the usage is incorrect，
`ctx.sql("select 1").explain()` is work well

**Comment by guojidan** [comment] 2024-02-23 02:36
https://arrow.apache.org/datafusion-python/generated/datafusion.DataFrame.html#datafusion.DataFrame.explain

**Comment by l1t1** [comment] 2024-02-23 02:57
does the explain method in [DataFrame.explain](https://arrow.apache.org/datafusion-python/generated/datafusion.DataFrame.html#datafusion.DataFrame.explain) need run the sql first?
if the sql took long time to execute, a logical plan without running it is needed.

**Comment by guojidan** [comment] 2024-02-23 03:05
DataFrame.explain function just build a explain LogicalPlan, same like excute `explain analyze select 1` sql

**Comment by l1t1** [comment] 2024-02-23 14:14
databend support following code, explain analyze took longer time
```python
import databend 
ctx=databend.SessionContext()

s2="""
WITH t AS( SELECT i, i*i*i*i*i::bigint AS i5 FROM(select number+1 i from numbers(150))),
t4 as ( SELECT a.i ai, b.i bi, c.i ci, d.i di,a.i5 + b.i5 + c.i5 + d.i5 i5 FROM t a, t b, t c, t d WHERE a.i < b.i AND b.i < c.i AND c.i < d.i)
select  ai,bi,ci,di,e.i ei from t4,t e where t4.di < e.i AND  t4.i5=e.i5;
"""

ctx.sql("explain "+s2)  #very fast
ctx.sql("explain analyze "+s2) # longer than ctx.sql(s2)
```

**Comment by Jefffrey** [comment] 2024-02-23 21:36
I've raised https://github.com/apache/arrow-datafusion-python/issues/589, as seems to be an issue with the Python bindings as identified by @SteveLauC 

I think we can close this as not an issue on the Rust lib side :+1:

**Closed** 2024-02-23 22:24 UTC
Labels: bug
