### ISSUE TITLE
Implement physical plan for IN Subquery

### ISSUE THREAD

**Issue by yahoNanJing** [apache/arrow-datafusion#1835] opened 2022-02-15 04:40 UTC
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Implement subqueries like 

```sql
SELECT f.x  FROM foo as f WHERE f.x IN  (select a from bar) as sq;
```

**Describe the solution you'd like**
It would be nice to use a SEMI join for this, something like

```
Projection(f.x, sq.a)
  --> Join(Semi f.x = sq.a)
    --> TableScan(foo)
    --> Projection(a)  <--- Here is where the "subquery"'s LogicalPlan is attached 
      --> TableScan(bar)
```

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment] 2022-04-08 17:52
Probably a dupe of https://github.com/apache/arrow-datafusion/issues/1209

**Comment by ygf11** [comment] 2023-03-06 03:46
I think this has already done. 

```sql
❯ explain select t1_id from t1 where t1_id in (select t2_id from t2);
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                            |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | LeftSemi Join: t1.t1_id = __correlated_sq_1.t2_id                                                                                               |
|               |   TableScan: t1 projection=[t1_id]                                                                                                              |
|               |   SubqueryAlias: __correlated_sq_1                                                                                                              |
|               |     Projection: t2.t2_id AS t2_id                                                                                                               |
|               |       TableScan: t2 projection=[t2_id]                                                                                                          |
...
❯ explain select t1_id from t1 where t1_id in (select t2_id from t2 where t2_int > t1_int);
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                                                                                                       |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: t1.t1_id                                                                                                                                                                                                                                       |
|               |   LeftSemi Join: t1.t1_id = __correlated_sq_2.t2_id Filter: __correlated_sq_2.t2_int > t1.t1_int                                                                                                                                                           |
|               |     TableScan: t1 projection=[t1_id, t1_int]                                                                                                                                                                                                               |
|               |     SubqueryAlias: __correlated_sq_2                                                                                                                                                                                                                       |
|               |       Projection: t2.t2_id AS t2_id, t2.t2_int                                                                                                                                                                                                             |
|               |         TableScan: t2 projection=[t2_id, t2_int]
```

**Closed** 2023-03-06 12:10 UTC
Labels: enhancement
