### ISSUE TITLE
implement unnest function

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1608] opened 2022-01-18 15:42 UTC
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

add `unnest` function that converts the argument into 0 or more rows.
1. the argument has to be of list type
2. the argument can be array literal or an array of list, in which case the expanded rows are unioned together

**Describe the solution you'd like**

similar to https://www.postgresql.org/docs/current/functions-array.html

**Describe alternatives you've considered**

**Additional context**

**Comment by lightjacket** [comment] 2022-01-18 15:43
This is a duplicate of https://github.com/apache/arrow-datafusion/issues/212

**Comment by vincev** [comment] 2023-02-12 15:11
Added some updates in #212.

**Closed** 2024-04-15 11:05 UTC
Labels: enhancement
