### ISSUE TITLE
  Make DataFrame extensible

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#190] opened 2021-04-26 13:32 UTC
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-12064

The DataFrame implementation currently has two types of logic:
 # Logic for building a logical query plan
 # Logic for executing a query using the DataFusion context

We can make DataFrame more extensible by having it always delegate to the context for execution, allowing the same DataFrame logic to be used for local and distributed execution.

We will likely need to introduce a new ExecutionContext trait with different implementations for DataFusion and Ballista.

**Comment by andygrove** [comment] 2021-04-26 13:42
Duplicate of https://github.com/apache/arrow-datafusion/issues/62

**Closed by andygrove** 2021-04-26 13:42 UTC
Labels: datafusion
