### ISSUE TITLE
Release DataFusion 16

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#4776] opened 2022-12-30 14:52 UTC
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
It has been ~4 weeks since the last release. I would like to release the next version soon (aiming for Friday, Jan 6).

**Describe the solution you'd like**

## Release tasks

- [x] Confirm that project is still compatible with Python bindings
- [x] Run benchmarks and confirm no major regressions

## Post-release tasks

- [x] #4804
- [x] Publish user guide: https://github.com/apache/arrow-site/pull/301

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment] 2022-12-31 11:06
> Confirm that project is still compatible with Python bindings

Do let me know if I've broken anything and I'll try to help out. I think I'm mostly done with the major changes, I can probably defer async catalog support until after the release

**Comment by andygrove** [comment] 2023-01-02 20:21
@tustvold I managed to bulldoze my way through getting the Python bindings working in https://github.com/apache/arrow-datafusion-python/pull/115. Please take a look if you have the time.

I have one issue to fix around window functions, and I will look at that later this week.

**Comment by alamb** [comment] 2023-01-04 19:02
FYI we found some issues with 30.0.0: https://github.com/apache/arrow-rs/issues/3455

**Comment by andygrove** [comment] 2023-01-10 17:04
The first RC seems to have an issue, so I will plan on creating a new RC once https://github.com/apache/arrow-datafusion/pull/4869 is merged.

**Comment by liukun4515** [comment] 2023-01-11 13:38
> The first RC seems to have an issue, so I will plan on creating a new RC once #4869 is merged.

merged, Thanks @ygf11 

You can create the RC for 16.0.0. cc @andygrove

**Comment by alamb** [comment] 2023-01-11 20:35
Checking them out

**Comment by alamb** [comment] 2023-01-11 20:49
https://github.com/apache/arrow-datafusion/issues/4875 looks serious but I could not reproduce it (more details in the ticket)

I think https://github.com/apache/arrow-datafusion/issues/4876 is expected

**Comment by DDtKey** [comment] 2023-01-12 16:01
JFYI: as it was discussed - #4875 isn't regression, but the bug existed before.
While #4876 is partially expected.

So probably it doesn't lock release, but it's up to the `datafusion` team 🙂

**Comment by alamb** [comment] 2023-01-22 11:56
I think with https://github.com/apache/arrow-site/pull/301 this issue can now be closed

**Closed** 2023-01-22 14:17 UTC
Labels: enhancement
