### ISSUE TITLE
Remove redundant projection when querying a view

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#3248] opened 2022-08-24 14:27 UTC
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
PR https://github.com/apache/arrow-datafusion/pull/3242 fixes a correctness issue where a projection was being ignored. However, the physical plan now contains a redundant projection and it would be good to remove it.

Example:

```
DataFusion CLI v11.0.0
❯ create view v as select 1 as a, 2 as b, 3 as c;
0 rows in set. Query took 0.002 seconds.

❯ explain select * from (select b from v);
+---------------+---------------------------------------+
| plan_type     | plan                                  |
+---------------+---------------------------------------+
| logical_plan  | Projection: #v.b                      |
|               |   TableScan: v projection=[b]         |
| physical_plan | ProjectionExec: expr=[b@0 as b]       |
|               |   ProjectionExec: expr=[b@0 as b]     |
|               |     ProjectionExec: expr=[2 as b]     |
|               |       EmptyExec: produce_one_row=true |
|               |                                       |
+---------------+---------------------------------------+
2 rows in set. Query took 0.009 seconds.
```
The physical plan returned from `ViewTable::scan` is:

```
ProjectionExec: expr=[b@0 as b]
  ProjectionExec: expr=[2 as b]
    EmptyExec: produce_one_row=true
```

The physical plan shown in the `EXPLAIN` query above has an additional redundant projection added.

**Describe the solution you'd like**
Remove the redundant projection.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by comphead** [comment] 2022-08-29 17:26
@andygrove I'll take it

**Comment by comphead** [comment] 2022-09-02 17:30
The problem is 
```
❯ create view v as select 1 as a, 2 as b, 3 as c;
0 rows in set. Query took 0.001 seconds.
❯ explain select * from (select b from v);
+---------------+---------------------------------------+
| plan_type     | plan                                  |
+---------------+---------------------------------------+
| logical_plan  | Projection: #v.b                      |
|               |   TableScan: v projection=[b]         |
| physical_plan | ProjectionExec: expr=[b@0 as b]       |
|               |   ProjectionExec: expr=[b@0 as b]     |
|               |     ProjectionExec: expr=[2 as b]     |
|               |       EmptyExec: produce_one_row=true |
|               |                                       |
+---------------+---------------------------------------+
```
The same for table 
```
❯ create table  v1 as select 1 as a, 2 as b, 3 as c;
+---+---+---+
| a | b | c |
+---+---+---+
| 1 | 2 | 3 |
+---+---+---+
1 row in set. Query took 0.003 seconds.
❯ explain select * from (select b from v1);
+---------------+-------------------------------------------------+
| plan_type     | plan                                            |
+---------------+-------------------------------------------------+
| logical_plan  | Projection: #v1.b                               |
|               |   TableScan: v1 projection=[b]                  |
| physical_plan | ProjectionExec: expr=[b@0 as b]                 |
|               |   MemoryExec: partitions=1, partition_sizes=[1] |
|               |                                                 |
+---------------+-------------------------------------------------+
```
@andygrove afaik those physical plans should be the same?

**Comment by HaoYang670** [comment] 2022-09-04 02:53
Hi @andygrove  @alamb  @comphead, I guess both this issue and #3249 can be solved by unfolding `view` as a subquery:
```
❯ create view v as select 1 as a, 2 as b, 3 as c;
0 rows in set. Query took 0.009 seconds.
❯ explain select * from (select b from v);
+---------------+---------------------------------------+
| plan_type     | plan                                  |
+---------------+---------------------------------------+
| logical_plan  | Projection: #v.b                      |
|               |   TableScan: v projection=[b]         |
| physical_plan | ProjectionExec: expr=[b@0 as b]       |
|               |   ProjectionExec: expr=[b@0 as b]     |
|               |     ProjectionExec: expr=[2 as b]     |
|               |       EmptyExec: produce_one_row=true |
|               |                                       |
+---------------+---------------------------------------+
2 rows in set. Query took 0.006 seconds.
❯ explain select * from (select b from (select 1 as a, 2 as b, 3 as c));
+---------------+-------------------------------------+
| plan_type     | plan                                |
+---------------+-------------------------------------+
| logical_plan  | Projection: #b                      |
|               |   Projection: Int64(2) AS b         |
|               |     EmptyRelation                   |
| physical_plan | ProjectionExec: expr=[b@0 as b]     |
|               |   ProjectionExec: expr=[2 as b]     |
|               |     EmptyExec: produce_one_row=true |
|               |                                     |
+---------------+-------------------------------------+
2 rows in set. Query took 0.005 seconds.
```

**Comment by Dandandan** [comment] 2022-09-05 20:26
Can we close this issue in favor of https://github.com/apache/arrow-datafusion/issues/3249 ?

**Comment by HaoYang670** [comment] 2022-09-06 02:58
> Can we close this issue in favor of https://github.com/apache/arrow-datafusion/issues/3249 ?

We should file a PR to close both this issue and 3249.

**Comment by alamb** [comment] 2023-03-24 19:53
This appears to be complete now:

```
git alamb@MacBook-Pro-8:~/Software/influxdb_iox/flightsql/src$ datafusion-cli
DataFusion CLI v20.0.0
❯ create view v as select 1 as a, 2 as b, 3 as c;
0 rows in set. Query took 0.022 seconds.
❯ explain select * from (select b from v);
+---------------+-----------------------------------+
| plan_type     | plan                              |
+---------------+-----------------------------------+
| logical_plan  | SubqueryAlias: v                  |
|               |   Projection: Int64(2) AS b       |
|               |     EmptyRelation                 |
| physical_plan | ProjectionExec: expr=[2 as b]     |
|               |   EmptyExec: produce_one_row=true |
|               |                                   |
+---------------+-----------------------------------+
```

**Closed by alamb** 2023-03-24 19:53 UTC
Labels: enhancement, performance
