### ISSUE TITLE
`create table as select ` should not print the output of the `select cause`

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-datafusion#6377] opened 2023-05-18 06:23 UTC
### Describe the bug

`create table as select` should not print the output of the `select ` cause.
```
❯ create table f as  select 1;
+----------+
| Int64(1) |
+----------+
| 1        |
+----------+
```

### To Reproduce

```
❯ create table f as  select 1;
+----------+
| Int64(1) |
+----------+
| 1        |
+----------+
```

**Comment by alamb** [comment] 2023-05-19 19:28
🤔 

Using datafusion-cli I was not able to reproduce this behavior

```shell
$ datafusion-cli
DataFusion CLI v24.0.0
❯ create table foo as select '1';
0 rows in set. Query took 0.021 seconds.
❯ create table bar as select * from foo;
0 rows in set. Query took 0.003 seconds.
```

**Comment by r4ntix** [comment] 2023-05-23 02:40
The problem is not reproduced in the current main branch:
```shell
$ datafusion-cli
DataFusion CLI v25.0.0
❯ create table f as  select 1;
0 rows in set. Query took 0.011 seconds
```

**Comment by alamb** [comment] 2023-05-23 11:14
Closing -- we can reopen if we get a reproducer

**Closed by alamb** 2023-05-23 11:14 UTC
Labels: bug
