### ISSUE TITLE
Improve the `Expr` string format

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#3878] opened 2022-10-18 13:56 UTC
We need improve the `Expr` fmt: like

```
let expr1 = and(a_1.clone(), b_2.clone())
            .and(a_2.clone())
            .and(b_1.clone());

        let expr2 = and(and(a_1.clone(), b_2.clone()), and(a_2.clone(), b_1.clone()));
        assert_eq!(expr1, expr2);
```

This is not equal but they have the same string format:

```
a = Int64(1) AND b = Int64(2) AND a = Int64(2) AND b = Int64(1)
```

_Originally posted by @Ted-Jiang in https://github.com/apache/arrow-datafusion/pull/3859#discussion_r998268672_

**Comment by andygrove** [comment] 2022-10-18 14:11
This seems like a duplicate of https://github.com/apache/arrow-datafusion/issues/3865?

**Comment by Ted-Jiang** [comment] 2022-10-19 03:10
> This seems like a duplicate of #3865?

Yes, it bother me when writing test 😂

**Comment by Ted-Jiang** [comment] 2022-10-19 03:10
@andygrove  We must print the priority of the `Expr`.

**Closed** 2022-10-25 08:27 UTC
