### ISSUE TITLE
CREATE EXTERNAL TABLE sql should check if table exists before doing IO

### ISSUE THREAD

**Issue by matthewmturner** [apache/arrow-datafusion#1871] opened 2022-02-22 06:25 UTC
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)
I was using datafusion-cli to test some sql queries on a large csv (for db-benchmark).  It takes a while for the table to be created as it is a large csv.  I ran the `CREATE EXTERNAL TABLE` command twice in the same session and got the error `Execution("The table x already exists")`.  However i had to wait the full time for IO to complete before the error showed up which i think is a waste of time.  I believe this is because we are running IO before checking if table exists.

**Describe the solution you'd like**
We should check if a table exists before doing IO and raise the table already exists error if it already exists.

**Describe alternatives you've considered**

**Additional context**

**Comment by kmitchener** [comment] 2022-09-26 17:53
This was resolved when we switched the CREATE TABLE / CREATE EXTERNAL TABLE commands to return empty dataframes. Can't reproduce this issue anymore. Can we close it?

**Closed** 2023-07-21 13:01 UTC
Labels: enhancement
