### ISSUE TITLE
Add documentation on supported functions to datafusion website

### ISSUE THREAD

**Issue by matthewmturner** [apache/arrow-datafusion#1487] opened 2021-12-26 04:07 UTC
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
It would be nice to publish to the datafusion website the supported functions.  I currently use AWS athena / presto and frequently reference their documentation (https://prestodb.io/docs/current/functions.html) on supported functions.  I am looking for datafusion to have something similar.

**Describe the solution you'd like**
Documentation of supported functions added to datafusion website

**Describe alternatives you've considered**

**Additional context**

**Comment by liukun4515** [comment] 2021-12-26 10:21
Do you have time to do this?
@matthewmturner

**Comment by matthewmturner** [comment] 2021-12-26 14:05
> Do you have time to do this?
> 
> @matthewmturner 

I likely won't have time in the near future. But will work on after closing my other issues if it's still available.

**Comment by matthewmturner** [comment] 2021-12-27 14:14
I found https://arrow.apache.org/datafusion/python/generated/datafusion.functions.html#module-datafusion.functions on the current website.

Assuming its expected that the available functions will be the same in rust and python then i think we could pull this out of the functions section and add a Functions section under User Guide.  that being said, i havent looked at the code for website yet and not sure if this links directly to python codebase or if we can move it.

finally, im used to using sql with datafusion but i think would need to be checked that functions are also available for use with dataframe.

**Comment by andygrove** [comment] 2022-08-11 13:53
I think this issue can be closed as a duplicate of https://github.com/apache/arrow-datafusion/issues/3065 and https://github.com/apache/arrow-datafusion/issues/3066 (which have been largely addressed now) but feel free to re-open if I am missing anything.

**Closed by andygrove** 2022-08-11 13:53 UTC
Labels: enhancement, good first issue, help wanted
