### ISSUE TITLE
Internal error: The "regex_replace" function can only accept strings

### ISSUE THREAD

**Issue by JayjeetAtGithub** [apache/arrow-datafusion#7345] opened 2023-08-21 06:05 UTC
### Describe the bug

On running the query below on the Clickbench multi file dataset, 

```sql
SELECT REGEXP_REPLACE("Referer", '^https?://(?:www.)?([^/]+)/.*$', '1') AS k, AVG(length("Referer")) AS l, COUNT(*) AS c, MIN("Referer") FROM hits WHERE "Referer" <> '' GROUP BY k HAVING COUNT(*) > 100000 ORDER BY l DESC LIMIT 25;
```

we get this error,

```bash
Internal error: The "regex_replace" function can only accept strings.. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

### To Reproduce

Download the data using,

```bash
 ./benchmarks/bench.sh data clickbench_partitioned
```

A `hits_multi` directory with the parquet files will be created.

Execute the above queries,

```bash
datafusion-cli -c "CREATE EXTERNAL TABLE hits STORED AS PARQUET LOCATION 'hits_multi';" "{query}"
```

### Expected behavior

The queries should run successfully without erroring.

### Additional context

Datafusion 29.0.0

**Comment by alamb** [comment] 2023-08-21 11:04
This looks similar to https://github.com/apache/arrow-datafusion/issues/7039 which @jonahgao  fixed by adding a coercion from binary --> UTF8 for comparison. I think we could do something similar here.

**Comment by alamb** [comment] 2023-08-21 11:05
Marking as a good first issue as there is a reproducer and I think the fix should be relatively straightforward

**Comment by Weijun-H** [comment] 2023-08-22 00:14
I am glad to fix it.

**Comment by Weijun-H** [comment] 2023-08-22 04:29
> ```shell
> Internal error: The "regex_replace" function can only accept strings.. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
> ```
This issue has been fixed. And following problem is `External error: Internal error: Min/Max accumulator not implemented for type Binary. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker`. 

Should we need to support ``Binary` for `MIN/MAX`?

**Closed** 2023-10-18 21:23 UTC
Labels: bug, good first issue
