### ISSUE TITLE
Use `parquet2` async reader in `physical_plan/parquet`

### ISSUE THREAD

**Issue by yjshen** [apache/arrow-datafusion#1058] opened 2021-09-27 07:25 UTC
This issue relies on https://github.com/apache/arrow-datafusion/pull/1010 as well as https://github.com/rdettai/arrow-datafusion/pull/1.

Please revisit `physical_plan/parquet` of all dead codes and unused variables for a throughout consideration.

**Comment by alamb** [comment] 2022-01-13 21:11
see also https://github.com/apache/arrow-datafusion/issues/1532

**Comment by tustvold** [comment] 2022-10-20 00:34
Closing as duplicate of #1532

**Closed by tustvold** 2022-10-20 00:34 UTC
Labels: enhancement
