### ISSUE TITLE
UDF/UDAF/UDWF: refactor ReturnType

### ISSUE THREAD

**Issue by JasonLi-cn** [apache/arrow-datafusion#8182] opened 2023-11-15 01:44 UTC
### Def one UDF: 

```rust
my_udf(expr, 'return_type')
```

### Using:

case1:
```rust
my_duf(col, 'UInt32')

Return Type is:
DataType::UInt32
```

case2:
```rust
my_duf(col, 'UInt64')

Return Type is:
DataType::UInt64
```

At present, the above udf cannot be realized through the `ReturnTypeFunction`. This is because the `ReturnTypeFunction` provides only the data types of the input parameters.

_Originally posted by @JasonLi-cn in https://github.com/apache/arrow-datafusion/discussions/7657_

**Comment by JasonLi-cn** [comment] 2023-11-15 01:45
https://github.com/apache/arrow-datafusion/discussions/7657

**Comment by alamb** [comment] 2024-04-12 09:49
Dupe of https://github.com/apache/arrow-datafusion/issues/8624

**Closed by alamb** 2024-04-12 09:49 UTC
