### ISSUE TITLE
Cannot query external table - TableScan replaced with EmptyExec

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#4027] opened 2022-10-29 22:00 UTC
**Describe the bug**
I am using the CLI to try and query a file. It shows that the file has no data but this is not the case.

**To Reproduce**

```
create external table partsupp (ps_partkey int, ps_suppkey int, ps_availqty int, ps_supplycost float, ps_comment varchar) stored as csv with delimiter '|' location '../benchmarks/data/partsupp.tbl';

❯ select count(*) from partsupp;
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 0               |
+-----------------+
1 row in set. Query took 0.001 seconds.
```

```
explain verbose select count(*) from partsupp;
```

```
| logical_plan                                               | Projection: COUNT(UInt8(1))                                     |
|                                                            |   Aggregate: groupBy=[[]], aggr=[[COUNT(UInt8(1))]]             |
|                                                            |     TableScan: partsupp projection=[ps_partkey]                 |
| initial_physical_plan                                      | ProjectionExec: expr=[COUNT(UInt8(1))@0 as COUNT(UInt8(1))]     |
|                                                            |   AggregateExec: mode=Final, gby=[], aggr=[COUNT(UInt8(1))]     |
|                                                            |     AggregateExec: mode=Partial, gby=[], aggr=[COUNT(UInt8(1))] |
|                                                            |       EmptyExec: produce_one_row=false     
```

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment] 2022-10-29 22:37
Looks like a duplicate of https://github.com/apache/arrow-datafusion/issues/1736

**Closed** 2022-10-30 14:15 UTC
Labels: bug
