### ISSUE TITLE
Using the window function lag causes panic.

### ISSUE THREAD

**Issue by ZuoTiJia** [apache/arrow-datafusion#3830] opened 2022-10-14 02:50 UTC
**Describe the bug**

When I create a table and use the lag window function, it panics

**To Reproduce**
```shell
DataFusion CLI v13.0.0
❯ create table foo AS values(1), (9223372036854775807);
0 rows in set. Query took 0.019 seconds.
❯ select lag(column1, column1, column1) over() from foo;
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', 
.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-13.0.0/src/physical_plan/windows/mod.rs:79:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Additional context**
Datafusion 13.0.0
MacBook Pro Apple M1

**Comment by alamb** [comment] 2022-10-22 10:58
Thanks for the report @ZuoTiJia 

cc @mustafasrepo and @ozankabak who I know have been working in this area recently

**Comment by ozankabak** [comment] 2022-10-22 14:38
Good catch! We will take a look at this and try to fix it early next week.

**Comment by mustafasrepo** [comment] 2022-10-25 11:46
I have traced the cause of this issue. The relevant section is [here](https://github.com/apache/arrow-datafusion/blob/7559c4425e6f32655c6d09e8ed17c9c51896472b/datafusion/core/src/physical_plan/windows/mod.rs#L101) for anyone trying to solve this issue. It seems that currently there is no support for expressions for the second (offset value) and the third(default value) field of the 'lag' function. API expects these fields to be 'literal'.

**Comment by ozankabak** [comment] 2022-10-25 15:32
Since this seems like an API issue rather than an execution issue, we will de-pri it on our end for now. We will circle back to this in the mid-term. If anyone needs it fixed in the short-term, we will be happy to provide further pointers.

**Comment by alamb** [comment] 2022-10-25 16:33
Thanks for the investigation @mustafasrepo  and @ozankabak 

Perhaps we can change the code to generate an error (rather than a panic) to more clearly explain to users what the probelm is

**Comment by alamb** [comment] 2022-10-27 14:29
I think we fixed the panic here: https://github.com/apache/arrow-datafusion/pull/3963

We can file a follow on ticket to support expressions in the window size, if needed. Thanks everyone!

**Closed by alamb** 2022-10-27 14:29 UTC
Labels: bug, good first issue
