### ISSUE TITLE
Possible performance regressions

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#5061] opened 2023-01-25 16:09 UTC
**Describe the bug**

I'm not 100% sure, but it looks like there may be performance regressions in DF 16. It could just be that some of these queries are quite variable in performance though.

This is average of 3 iterations of each query.

![image](https://user-images.githubusercontent.com/934084/214614689-2e064648-36f4-4ca8-9056-a1852e58e014.png)

**To Reproduce**

**Expected behavior**

**Additional context**
https://sqlbenchmarks.io/sqlbench-h/results/env/workstation/sf10/single_node/

**Comment by ozankabak** [comment] 2023-01-28 17:55
We are planning to dedicate some time into improving performance after we are done with the current features we are building (better optimizations, non-pipeline-breaking pruning symmetric hash join etc.). If this is a real regression and we can identify the cause, we can help fix/improve this in the upcoming weeks.

**Comment by mingmwang** [comment] 2023-02-16 05:31
Is it possible to add and compare the physical plan differences when we run the bench ?

**Comment by Dandandan** [comment] 2023-07-01 09:59
I think we can close it, this may have had to do with casting / type coercion changes which have been fixed.

**Closed by Dandandan** 2023-07-01 09:59 UTC
Labels: bug
